basePath: /
host: localhost:8080
info:
  contact:
    email: yifanguo247@gmail.com
    name: Yifan Guo
    url: https://github.com/yifan-guo/FlightTracker
  description: This is REST API server to determine the flight.go path of a person.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Flight Path API
  version: "1.0"
paths:
  /calculate:
    post:
      parameters:
      - description: Flight segments
        in: body
        name: flightSegments
        required: true
        schema:
          items:
            items:
              type: string
            type: array
          type: array
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request Error
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
schemes:
- http
swagger: "2.0"
